### ISSUE TITLE
Terminal theme in the future?

### ISSUE THREAD

**Issue by iamajvillalobos** [thenikso/github-plus-theme#1]
I'm really digging this theme. Will there be a hyper or iterm2 theme? :)

**Comment by zhengger** [comment]
Sir, Can you add the theme to the integrated terminal. Please!!

**Comment by shytikov** [comment]
Yes, the integrated VSCode terminal currently looks a bit ugly with the given theme... It would be nice to have it fixed someday...

**Comment by thenikso** [comment]
Just added these in 1.4.0. Please let me know if it working for you all!
I had a custom mac terminal theme that vscode was inheriting so I never noticed the problem :|
