### ISSUE TITLE
contrast issue on selected files and quick action dropdown

### ISSUE THREAD

**Issue by wiedikerli** [thenikso/github-plus-theme#12]
i cannot read the name of the selected file:
![screenshot-1](https://user-images.githubusercontent.com/2211563/59354708-e3671200-8d25-11e9-94ef-0135124109f3.jpg)

and also the quick action dropdown has this issue with the selected item:
![screenshot-2](https://user-images.githubusercontent.com/2211563/59354709-e3671200-8d25-11e9-9e2a-5a7cc2183595.jpg)

**Comment by thenikso** [comment]
This should have been solved a while back. let me know if the problem persists with the latest version of the theme
