### ISSUE TITLE
Add support for inputOption.activeBackground

### ISSUE THREAD

**Issue by miguelsolorio** [thenikso/github-plus-theme#13]
VS Code will be introducing a new token color, `inputOption.activeBackground`, in the July release (1.37). This color is for showing when a button toggle is active (search, find, terminal find, etc.). It also re-uses `focusBorder` but in this theme the focus color is set to transparent, which means the new token color is also transparent. See below where you can't tell which item is "active", please consider adding support for this. You can test this by using the [Insiders version](https://code.visualstudio.com/insiders/), which already adds this.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/35271042/62474117-07a80380-b757-11e9-9e18-302633731397.png">

**Comment by thenikso** [comment]
yep, that's been added a while back. this is what you should see with the latest version of the theme

![Screenshot 2021-08-26 at 12 19 01](https://user-images.githubusercontent.com/1614904/130946118-14a45878-df5e-4040-9604-ff3064e8dddf.jpg)
