### ISSUE TITLE
Intellisense selected text matches background color making it impossible to see

### ISSUE THREAD

**Issue by trafnar** [thenikso/github-plus-theme#20]
After updating vscode to 1.57.0, the background color of the intellisense popup selected item matches the color of the highlighted text making it invisible.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/6732/122123735-31b2be00-cde3-11eb-9b7f-4731d1bc2a4a.png">

If anyone else is having this problem, I temporarily fixed it by adding these lines to my settings.json file:

```json
  "workbench.colorCustomizations": {
    "editorSuggestWidget.selectedBackground": "#B1DAFF",
    "editorSuggestWidget.selectedForeground": "#24292E"
  }
```

**Comment by daveed** [comment]
I also had that issue for the quick open (Command-P):

```
  "workbench.colorCustomizations": {
    "editorSuggestWidget.selectedBackground": "#B1DAFF",
    "editorSuggestWidget.selectedForeground": "#24292E",
    "quickInputList.focusBackground": "#B1DAFF",
    "quickInputList.focusForeground": "#24292E"
  }
```

**Comment by thenikso** [comment]
this problem was driving me nuts as well! with the latest 1.4.1 published version this should be fixed together with a tweak to `list.focusHighlightForeground`
