### ISSUE TITLE
Tree view: Arrow navigation item is not highlighter

### ISSUE THREAD

**Issue by JackVeromeev** [thenikso/github-plus-theme#21]
Hello.
Thank you for the delightful colour theme!
I have a little issue in the left-side tree view in the git tree navigation.
If I select a folder item by a mouse and then expand it or jump up/down by an arrow, I don't see any highlight on the item, only the GitLens helping icons help 😄 . But in the Project Explorer view there are no icons, and I see absolutely nothing

On the screenshot below you can see I clicked on the `manifest` folder, then expanded it and went down to the `objects.xml` file.

The environment:
OS: MacOS Big Sur 14.01
VSCode: Version: 1.60.0
Github Plus Theme version (last bullet from CHANGELOG): [1.4.0] - 2021-08-26

![image](https://user-images.githubusercontent.com/15068679/133426705-b96e02e0-b38b-4ded-b405-c4f6452af32c.png)

**Comment by thenikso** [comment]
nice catch! fixed in 1.4.3
