### ISSUE TITLE
Change CSS values color

### ISSUE THREAD

**Issue by bezvoshchuk** [thenikso/github-plus-theme#3]
Hey Nicola! 
Thank you for the awesome theme!
Everything is nice in it, I switched to it, but I think CSS looks a bit monotonous:

<img width="217" alt="screen shot 2017-11-29 at 00 05 50" src="https://user-images.githubusercontent.com/5589372/33349805-07ad4e8e-d49c-11e7-9160-0b2ff1e524e2.png">

In my opinion it would be much better if CSS values color was black.
What do you think about this?

**Comment by VitalyKrenel** [comment]
I believe your suggestion is quite meaningful.
But right now it's exactly like Github styling is applied. For some people it might be the case. 

Of course we should wait for maintainer's answer.

```css
.main-wait-bar.is-show {
  width: 100%;
  height: 100%;
  color: #000;
}
```

Probably, it would be better if you will apply the styling through your VS Code preferences by `editor.tokenColorCustomizations` using `textMateRules` property.

The value for "textMateRules" may be like this:

```json

 "editor.tokenColorCustomizations": {
  "textMateRules": [
     {
        "scope": [
          "constant.numeric.css",
          "support.constant.property-value.css",
          "support.function.misc.css",
          "constant.other.color.rgb-value.hex.css",
          "punctuation.section.function.begin.bracket.round.css",
          "punctuation.section.function.end.bracket.round.css"
        ],
        "settings": {
          "foreground": "#353535",
        }
      }
    ]
  }
 ```

The result will be something like this

<img src="https://user-images.githubusercontent.com/17354709/41204862-c17e7ab0-6cf2-11e8-9fbd-967339939ddd.png" alt="Changed syntax styling" width="400">

Sure, there are some CSS language entities that are not covered by this rule set, but you may want them to be applied. For such a case, I recommend you to see [this official guide](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_textmate-theme-rules)

**Comment by thenikso** [comment]
thanks a lot! I've added these here 66a076a737942fdde17ab991461d9bb49c829aff and will publish soon
