### ISSUE TITLE
Color of dots in .js files

### ISSUE THREAD

**Issue by technoiswatchingyou** [thenikso/github-plus-theme#6]
Hi

Is it possible to change dots color? I mean that comma, for example, is white and 3 dots is read. But one dot is black (or some dark color, no matter). It's probably would be more readable if single dot will be like comma.

![screen shot 2018-10-03 at 11 33 58 pm](https://user-images.githubusercontent.com/25575840/46413829-2ae3da00-c765-11e8-90b2-b424867f79ef.png)

Thanks,
Andrei

UPDATE: Problem is that your theme in conflict with all Babel packages.

**Comment by thenikso** [comment]
how do you get the background to be dark? probably via the same method you also want to change the color of those dots. specifically this scope:

```json
{
      "scope": [
        "keyword.operator.accessor",
        "meta.group.braces.round.function.arguments",
        "meta.template.expression",
        "markup.fenced_code meta.embedded.block"
      ],
      "settings": {
        "foreground": "#24292eff"
      }
    }
```
