### ISSUE TITLE
Template Literal Interpolation Expressions Unreadable in Markdown Preview.

### ISSUE THREAD

**Issue by rbiggs** [thenikso/github-plus-theme#7]
I love this theme, but template literals that have interpolation expressions are unreadable in Markdown previews.

If I create a markdown file with a code block:

\```javascript
if (refs.has('input')) {
  console.log(`Input value is: ${refs.get('input').value}.`)
} 
\```

And then open the file in Markdown preview mode, the part `${refs.get('input').value}`, which is an interpolation expression, is unreadable:
<img width="690" alt="screen shot 2018-10-12 at 4 44 21 am" src="https://user-images.githubusercontent.com/249218/46867660-a3d4d880-cdda-11e8-8700-15357710f3d2.png">

**Comment by thenikso** [comment]
this theme do not provide a markdown preview style. you should get one like [this](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles) or [create your own](https://gist.github.com/JamesMessinger/5d31c053d0b1d52389eb2723f7550907)
