### ISSUE TITLE
Brackets and variables not visually different in template literal strings

### ISSUE THREAD

**Issue by jayporta** [thenikso/github-plus-theme#9]
I'm on the latest version available through the Visual Studio marketplace. Attached is a screenshot from this theme, and below it is Octocat in Atom. I don't expect them to be exactly the same or anything, and I like that strings are green, but the curly brackets and variable inside aren't differentiated. 

I'd love to submit a PR but I've never made or even modified a VSCode theme. I'll try to learn. Also if anyone could give me some hints on how to specifically target the curly brackets maybe I can figure it out. 

![Screen Shot 2019-03-12 at 12 35 05 PM](https://user-images.githubusercontent.com/15250836/54218116-4fd23b00-44c3-11e9-8a83-cb8117692bbe.png)

![Screen Shot 2019-03-12 at 12 36 19 PM](https://user-images.githubusercontent.com/15250836/54218348-c707cf00-44c3-11e9-92a3-a86588b853b0.png)

**Comment by thenikso** [comment]
This probably changed a while back. This is what you should see with the latest version of the theme:

![Screenshot 2021-08-26 at 12 10 31](https://user-images.githubusercontent.com/1614904/130944954-4b0e6b09-b9fb-4013-89cd-f52bacdd4f2d.jpg)
